
var fakeData = [ { id: 1, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe1.png', price: 125, category: "Men's Shoes"}

,{ id: 2, name: 'Air Force 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pellentesque, quam vel sodales elementum, nisi ipsum bibendum urna, elementum sagittis orci ligula in neque. Vestibulum dictum convallis ante, nec viverra.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe2.png', price: 85, category: "Womens Shoes"}

,{ id: 3, name: 'Air Jordan', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a quam imperdiet, auctor elit vel, mattis dui. Aenean feugiat maximus magna vitae cursus. Nullam gravida nisl sit amet urna mollis.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe3.png', price: 210, category: "Men's Shoes"}

,{ id: 4, name: 'Off Whites', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis pretium magna. Etiam mollis, nulla vel consectetur gravida, purus diam gravida augue, eget gravida ipsum felis in enim. In consectetur.', colors: ['black'], relatedShoes: [1, 2, 3, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe4.png', price: 165, category: "Womens Shoes"}

,{ id: 5, name: 'Lunar Epic Flyknit', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla luctus interdum erat. Mauris porttitor consequat elit at mattis. Proin vitae commodo dolor. Vivamus felis dolor, pretium a arcu a, lobortis.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe5.png', price: 180, category: "Men's Shoes"}

,{ id: 6, name: 'SB Boston Hyperfeel 3', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper, lorem luctus accumsan pretium, ex quam commodo elit, quis interdum ligula purus at tellus. Vestibulum ullamcorper diam ac vulputate porttitor.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe6.png', price: 90, category: "Womens Shoes"}

,{ id: 7, name: 'Air Max 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis cursus risus nec augue pellentesque, auctor dictum est blandit. Vestibulum auctor dictum lorem, non vehicula eros aliquam vel. Vivamus et suscipit.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe7.png', price: 75, category: "Men's Shoes"}

,{ id: 8, name: 'Air Rift 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non velit sapien. Ut dapibus vestibulum fringilla. In semper id risus eget tincidunt. Vestibulum vitae mauris quis dui malesuada cursus eu.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe8.png', price: 125, category: "Womens Shoes"}

,{ id: 9, name: 'Air Rift Wrap', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla aliquet, ante eu rhoncus fermentum, nisi lorem iaculis tortor, et pharetra eros leo et erat. Pellentesque eleifend ex ut egestas feugiat.', colors: ['black'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe9.png', price: 85, category: "Men's Shoes"}

,{ id: 10, name: 'Air Max 2', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel lacus suscipit eros lobortis vehicula. Aliquam dignissim risus elit, in blandit sapien tincidunt ac. Morbi massa diam, fringilla ut mi.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe10.png', price: 210, category: "Womens Shoes"}

,{ id: 11, name: 'Jordan XV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet auctor sapien, in facilisis quam. Sed condimentum nisl vel mauris malesuada, sed faucibus mi porta. Maecenas fermentum mattis nibh.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe11.png', price: 165, category: "Men's Shoes"}

,{ id: 12, name: 'Jordan XX1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec purus dictum, placerat enim eget, dapibus metus. Suspendisse potenti. Maecenas eu lorem nec sapien pulvinar pretium. Nulla mollis velit lorem.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe12.png', price: 180, category: "Womens Shoes"}

,{ id: 13, name: 'Jordan 2010', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc viverra turpis vitae leo malesuada elementum ut ut elit. Maecenas ut enim varius, sollicitudin nibh ac, dictum enim. Nunc dui lorem.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe13.png', price: 90, category: "Men's Shoes"}

,{ id: 14, name: 'Nike Zoom Air Huarache 2K4', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus in lectus semper volutpat. Vivamus sed suscipit nulla, vel hendrerit eros. Etiam efficitur tincidunt ex, at maximus diam gravida tincidunt.', colors: ['black'], relatedShoes: [2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe1.png', price: 75, category: "Womens Shoes"}

,{ id: 15, name: 'Nike Air Zoom Huarache 2K5', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at commodo nunc, ac ultricies urna. Sed malesuada placerat cursus. Sed eget eros dapibus, viverra nunc at, convallis odio. Fusce orci.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe2.png', price: 125, category: "Men's Shoes"}

,{ id: 16, name: 'Nike Zoom Kobe I', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed facilisis magna eros, id egestas magna euismod ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec a auctor.', colors: ['white', 'back'], relatedShoes: [1, 2, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe3.png', price: 85, category: "Womens Shoes"}

,{ id: 17, name: 'Nike Zoom Kobe III', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non eleifend erat, et dictum quam. Nam vehicula cursus justo, et varius risus tempus fermentum. Vivamus finibus luctus laoreet. Vivamus et.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe4.png', price: 210, category: "Men's Shoes"}

,{ id: 18, name: 'Nike Hyperfuse', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tortor risus, commodo vel est et, laoreet feugiat massa. Nullam varius blandit diam auctor tristique. Etiam fermentum dignissim justo et lacinia.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe5.png', price: 165, category: "Womens Shoes"}

,{ id: 19, name: 'Nike HyperDunk Kobe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dictum laoreet congue. Duis convallis, augue a ultricies eleifend, eros risus blandit nibh, non consequat ex nunc id eros. Etiam laoreet.', colors: ['black'], relatedShoes: [1, 2, 3, 4, 5, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe6.png', price: 180, category: "Men's Shoes"}

,{ id: 20, name: 'Nike Zoom Kobe VII', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non eleifend erat, et dictum quam. Nam vehicula cursus justo, et varius risus tempus fermentum. Vivamus finibus luctus laoreet. Vivamus et.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 5, 6, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe7.png', price: 90, category: "Womens Shoes"}

,{ id: 21, name: 'Nike Zoom Kobe Venomenom IV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at commodo nunc, ac ultricies urna. Sed malesuada placerat cursus. Sed eget eros dapibus, viverra nunc at, convallis odio. Fusce orci.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe8.png', price: 75, category: "Men's Shoes"}

,{ id: 22, name: 'Nike Zoom Kobe Venomenom IV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam bibendum nisl quam, sit amet aliquam leo vestibulum sit amet. Suspendisse venenatis vulputate dapibus. Nunc mauris ante, molestie sit amet metus.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe9.png', price: 125, category: "Womens Shoes"}

,{ id: 23, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe10.png', price: 125, category: "Men's Shoes"}

,{ id: 24, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe11.png', price: 125, category: "Men's Shoes"}

,{ id: 25, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe12.png', price: 125, category: "Men's Shoes"}

,{ id: 26, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe1.png', price: 125, category: "Men's Shoes"}


,{ id: 27, name: 'Air Force 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pellentesque, quam vel sodales elementum, nisi ipsum bibendum urna, elementum sagittis orci ligula in neque. Vestibulum dictum convallis ante, nec viverra.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe2.png', price: 85, category: "Womens Shoes"}

,{ id: 28, name: 'Air Jordan', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a quam imperdiet, auctor elit vel, mattis dui. Aenean feugiat maximus magna vitae cursus. Nullam gravida nisl sit amet urna mollis.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe3.png', price: 210, category: "Men's Shoes"}

,{ id: 29, name: 'Off Whites', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis pretium magna. Etiam mollis, nulla vel consectetur gravida, purus diam gravida augue, eget gravida ipsum felis in enim. In consectetur.', colors: ['black'], relatedShoes: [1, 2, 3, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe4.png', price: 165, category: "Womens Shoes"}

,{ id: 30, name: 'Lunar Epic Flyknit', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla luctus interdum erat. Mauris porttitor consequat elit at mattis. Proin vitae commodo dolor. Vivamus felis dolor, pretium a arcu a, lobortis.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe5.png', price: 180, category: "Men's Shoes"}

,{ id: 31, name: 'SB Boston Hyperfeel 3', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper, lorem luctus accumsan pretium, ex quam commodo elit, quis interdum ligula purus at tellus. Vestibulum ullamcorper diam ac vulputate porttitor.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe6.png', price: 90, category: "Womens Shoes"}

,{ id: 32, name: 'Air Max 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis cursus risus nec augue pellentesque, auctor dictum est blandit. Vestibulum auctor dictum lorem, non vehicula eros aliquam vel. Vivamus et suscipit.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe7.png', price: 75, category: "Men's Shoes"}

,{ id: 33, name: 'Air Rift 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non velit sapien. Ut dapibus vestibulum fringilla. In semper id risus eget tincidunt. Vestibulum vitae mauris quis dui malesuada cursus eu.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe8.png', price: 125, category: "Womens Shoes"}

,{ id: 34, name: 'Air Rift Wrap', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla aliquet, ante eu rhoncus fermentum, nisi lorem iaculis tortor, et pharetra eros leo et erat. Pellentesque eleifend ex ut egestas feugiat.', colors: ['black'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe9.png', price: 85, category: "Men's Shoes"}

,{ id: 35, name: 'Air Max 2', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel lacus suscipit eros lobortis vehicula. Aliquam dignissim risus elit, in blandit sapien tincidunt ac. Morbi massa diam, fringilla ut mi.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe10.png', price: 210, category: "Womens Shoes"}

,{ id: 36, name: 'Jordan XV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet auctor sapien, in facilisis quam. Sed condimentum nisl vel mauris malesuada, sed faucibus mi porta. Maecenas fermentum mattis nibh.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe11.png', price: 165, category: "Men's Shoes"}

,{ id: 37, name: 'Jordan XX1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec purus dictum, placerat enim eget, dapibus metus. Suspendisse potenti. Maecenas eu lorem nec sapien pulvinar pretium. Nulla mollis velit lorem.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe12.png', price: 180, category: "Womens Shoes"}

,{ id: 38, name: 'Jordan 2010', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc viverra turpis vitae leo malesuada elementum ut ut elit. Maecenas ut enim varius, sollicitudin nibh ac, dictum enim. Nunc dui lorem.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe13.png', price: 90, category: "Men's Shoes"}

,{ id: 39, name: 'Nike Zoom Air Huarache 2K4', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus in lectus semper volutpat. Vivamus sed suscipit nulla, vel hendrerit eros. Etiam efficitur tincidunt ex, at maximus diam gravida tincidunt.', colors: ['black'], relatedShoes: [2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe1.png', price: 75, category: "Womens Shoes"}

,{ id: 40, name: 'Nike Air Zoom Huarache 2K5', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at commodo nunc, ac ultricies urna. Sed malesuada placerat cursus. Sed eget eros dapibus, viverra nunc at, convallis odio. Fusce orci.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe2.png', price: 125, category: "Men's Shoes"}

,{ id: 41, name: 'Nike Zoom Kobe I', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed facilisis magna eros, id egestas magna euismod ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec a auctor.', colors: ['white', 'back'], relatedShoes: [1, 2, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe3.png', price: 85, category: "Womens Shoes"}

,{ id: 42, name: 'Nike Zoom Kobe III', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non eleifend erat, et dictum quam. Nam vehicula cursus justo, et varius risus tempus fermentum. Vivamus finibus luctus laoreet. Vivamus et.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe4.png', price: 210, category: "Men's Shoes"}

,{ id: 43, name: 'Nike Hyperfuse', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tortor risus, commodo vel est et, laoreet feugiat massa. Nullam varius blandit diam auctor tristique. Etiam fermentum dignissim justo et lacinia.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe5.png', price: 165, category: "Womens Shoes"}

,{ id: 44, name: 'Nike HyperDunk Kobe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dictum laoreet congue. Duis convallis, augue a ultricies eleifend, eros risus blandit nibh, non consequat ex nunc id eros. Etiam laoreet.', colors: ['black'], relatedShoes: [1, 2, 3, 4, 5, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe6.png', price: 180, category: "Men's Shoes"}

,{ id: 45, name: 'Nike Zoom Kobe VII', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non eleifend erat, et dictum quam. Nam vehicula cursus justo, et varius risus tempus fermentum. Vivamus finibus luctus laoreet. Vivamus et.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 5, 6, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe7.png', price: 90, category: "Womens Shoes"}

,{ id: 46, name: 'Nike Zoom Kobe Venomenom IV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at commodo nunc, ac ultricies urna. Sed malesuada placerat cursus. Sed eget eros dapibus, viverra nunc at, convallis odio. Fusce orci.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe8.png', price: 75, category: "Men's Shoes"}

,{ id: 47, name: 'Nike Zoom Kobe Venomenom IV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam bibendum nisl quam, sit amet aliquam leo vestibulum sit amet. Suspendisse venenatis vulputate dapibus. Nunc mauris ante, molestie sit amet metus.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe9.png', price: 125, category: "Womens Shoes"}

,{ id: 48, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe10.png', price: 125, category: "Men's Shoes"}

,{ id: 49, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe11.png', price: 125, category: "Men's Shoes"}

,{ id: 50, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe12.png', price: 125, category: "Men's Shoes"}

,{ id: 51, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe1.png', price: 125, category: "Men's Shoes"}


,{ id: 52, name: 'Air Force 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pellentesque, quam vel sodales elementum, nisi ipsum bibendum urna, elementum sagittis orci ligula in neque. Vestibulum dictum convallis ante, nec viverra.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe2.png', price: 85, category: "Womens Shoes"}

,{ id: 53, name: 'Air Jordan', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a quam imperdiet, auctor elit vel, mattis dui. Aenean feugiat maximus magna vitae cursus. Nullam gravida nisl sit amet urna mollis.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe3.png', price: 210, category: "Men's Shoes"}

,{ id: 54, name: 'Off Whites', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis pretium magna. Etiam mollis, nulla vel consectetur gravida, purus diam gravida augue, eget gravida ipsum felis in enim. In consectetur.', colors: ['black'], relatedShoes: [1, 2, 3, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe4.png', price: 165, category: "Womens Shoes"}

,{ id: 55, name: 'Lunar Epic Flyknit', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla luctus interdum erat. Mauris porttitor consequat elit at mattis. Proin vitae commodo dolor. Vivamus felis dolor, pretium a arcu a, lobortis.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe5.png', price: 180, category: "Men's Shoes"}

,{ id: 56, name: 'SB Boston Hyperfeel 3', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper, lorem luctus accumsan pretium, ex quam commodo elit, quis interdum ligula purus at tellus. Vestibulum ullamcorper diam ac vulputate porttitor.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe6.png', price: 90, category: "Womens Shoes"}

,{ id: 57, name: 'Air Max 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis cursus risus nec augue pellentesque, auctor dictum est blandit. Vestibulum auctor dictum lorem, non vehicula eros aliquam vel. Vivamus et suscipit.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe7.png', price: 75, category: "Men's Shoes"}

,{ id: 58, name: 'Air Rift 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non velit sapien. Ut dapibus vestibulum fringilla. In semper id risus eget tincidunt. Vestibulum vitae mauris quis dui malesuada cursus eu.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe8.png', price: 125, category: "Womens Shoes"}

,{ id: 59, name: 'Air Rift Wrap', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla aliquet, ante eu rhoncus fermentum, nisi lorem iaculis tortor, et pharetra eros leo et erat. Pellentesque eleifend ex ut egestas feugiat.', colors: ['black'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe9.png', price: 85, category: "Men's Shoes"}

,{ id: 60, name: 'Air Max 2', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel lacus suscipit eros lobortis vehicula. Aliquam dignissim risus elit, in blandit sapien tincidunt ac. Morbi massa diam, fringilla ut mi.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe10.png', price: 210, category: "Womens Shoes"}

,{ id: 61, name: 'Jordan XV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet auctor sapien, in facilisis quam. Sed condimentum nisl vel mauris malesuada, sed faucibus mi porta. Maecenas fermentum mattis nibh.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe11.png', price: 165, category: "Men's Shoes"}

,{ id: 62, name: 'Jordan XX1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec purus dictum, placerat enim eget, dapibus metus. Suspendisse potenti. Maecenas eu lorem nec sapien pulvinar pretium. Nulla mollis velit lorem.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe12.png', price: 180, category: "Womens Shoes"}

,{ id: 63, name: 'Jordan 2010', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc viverra turpis vitae leo malesuada elementum ut ut elit. Maecenas ut enim varius, sollicitudin nibh ac, dictum enim. Nunc dui lorem.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe13.png', price: 90, category: "Men's Shoes"}

,{ id: 64, name: 'Nike Zoom Air Huarache 2K4', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus in lectus semper volutpat. Vivamus sed suscipit nulla, vel hendrerit eros. Etiam efficitur tincidunt ex, at maximus diam gravida tincidunt.', colors: ['black'], relatedShoes: [2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe1.png', price: 75, category: "Womens Shoes"}

,{ id: 65, name: 'Nike Air Zoom Huarache 2K5', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at commodo nunc, ac ultricies urna. Sed malesuada placerat cursus. Sed eget eros dapibus, viverra nunc at, convallis odio. Fusce orci.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe2.png', price: 125, category: "Men's Shoes"}

,{ id: 66, name: 'Nike Zoom Kobe I', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed facilisis magna eros, id egestas magna euismod ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec a auctor.', colors: ['white', 'back'], relatedShoes: [1, 2, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe3.png', price: 85, category: "Womens Shoes"}

,{ id: 67, name: 'Nike Zoom Kobe III', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non eleifend erat, et dictum quam. Nam vehicula cursus justo, et varius risus tempus fermentum. Vivamus finibus luctus laoreet. Vivamus et.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe4.png', price: 210, category: "Men's Shoes"}

,{ id: 68, name: 'Nike Hyperfuse', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tortor risus, commodo vel est et, laoreet feugiat massa. Nullam varius blandit diam auctor tristique. Etiam fermentum dignissim justo et lacinia.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe5.png', price: 165, category: "Womens Shoes"}

,{ id: 69, name: 'Nike HyperDunk Kobe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dictum laoreet congue. Duis convallis, augue a ultricies eleifend, eros risus blandit nibh, non consequat ex nunc id eros. Etiam laoreet.', colors: ['black'], relatedShoes: [1, 2, 3, 4, 5, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe6.png', price: 180, category: "Men's Shoes"}

,{ id: 70, name: 'Nike Zoom Kobe VII', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non eleifend erat, et dictum quam. Nam vehicula cursus justo, et varius risus tempus fermentum. Vivamus finibus luctus laoreet. Vivamus et.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 5, 6, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe7.png', price: 90, category: "Womens Shoes"}

,{ id: 71, name: 'Nike Zoom Kobe Venomenom IV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at commodo nunc, ac ultricies urna. Sed malesuada placerat cursus. Sed eget eros dapibus, viverra nunc at, convallis odio. Fusce orci.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe8.png', price: 75, category: "Men's Shoes"}

,{ id: 72, name: 'Nike Zoom Kobe Venomenom IV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam bibendum nisl quam, sit amet aliquam leo vestibulum sit amet. Suspendisse venenatis vulputate dapibus. Nunc mauris ante, molestie sit amet metus.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe9.png', price: 125, category: "Womens Shoes"}

,{ id: 73, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe10.png', price: 125, category: "Men's Shoes"}

,{ id: 74, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe11.png', price: 125, category: "Men's Shoes"}

,{ id: 75, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe12.png', price: 125, category: "Men's Shoes"}

   ,{ id: 76, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe1.png', price: 125, category: "Men's Shoes"}


,{ id: 77, name: 'Air Force 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pellentesque, quam vel sodales elementum, nisi ipsum bibendum urna, elementum sagittis orci ligula in neque. Vestibulum dictum convallis ante, nec viverra.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe2.png', price: 85, category: "Womens Shoes"}

,{ id: 78, name: 'Air Jordan', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a quam imperdiet, auctor elit vel, mattis dui. Aenean feugiat maximus magna vitae cursus. Nullam gravida nisl sit amet urna mollis.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe3.png', price: 210, category: "Men's Shoes"}

,{ id: 79, name: 'Off Whites', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis pretium magna. Etiam mollis, nulla vel consectetur gravida, purus diam gravida augue, eget gravida ipsum felis in enim. In consectetur.', colors: ['black'], relatedShoes: [1, 2, 3, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe4.png', price: 165, category: "Womens Shoes"}

,{ id: 80, name: 'Lunar Epic Flyknit', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla luctus interdum erat. Mauris porttitor consequat elit at mattis. Proin vitae commodo dolor. Vivamus felis dolor, pretium a arcu a, lobortis.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe5.png', price: 180, category: "Men's Shoes"}

,{ id: 81, name: 'SB Boston Hyperfeel 3', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris semper, lorem luctus accumsan pretium, ex quam commodo elit, quis interdum ligula purus at tellus. Vestibulum ullamcorper diam ac vulputate porttitor.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe6.png', price: 90, category: "Womens Shoes"}

,{ id: 82, name: 'Air Max 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis cursus risus nec augue pellentesque, auctor dictum est blandit. Vestibulum auctor dictum lorem, non vehicula eros aliquam vel. Vivamus et suscipit.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe7.png', price: 75, category: "Men's Shoes"}

,{ id: 83, name: 'Air Rift 1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non velit sapien. Ut dapibus vestibulum fringilla. In semper id risus eget tincidunt. Vestibulum vitae mauris quis dui malesuada cursus eu.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe8.png', price: 125, category: "Womens Shoes"}

,{ id: 84, name: 'Air Rift Wrap', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla aliquet, ante eu rhoncus fermentum, nisi lorem iaculis tortor, et pharetra eros leo et erat. Pellentesque eleifend ex ut egestas feugiat.', colors: ['black'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe9.png', price: 85, category: "Men's Shoes"}

,{ id: 85, name: 'Air Max 2', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris vel lacus suscipit eros lobortis vehicula. Aliquam dignissim risus elit, in blandit sapien tincidunt ac. Morbi massa diam, fringilla ut mi.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe10.png', price: 210, category: "Womens Shoes"}

,{ id: 86, name: 'Jordan XV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sit amet auctor sapien, in facilisis quam. Sed condimentum nisl vel mauris malesuada, sed faucibus mi porta. Maecenas fermentum mattis nibh.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe11.png', price: 165, category: "Men's Shoes"}

,{ id: 87, name: 'Jordan XX1', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent nec purus dictum, placerat enim eget, dapibus metus. Suspendisse potenti. Maecenas eu lorem nec sapien pulvinar pretium. Nulla mollis velit lorem.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe12.png', price: 180, category: "Womens Shoes"}

,{ id: 88, name: 'Jordan 2010', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc viverra turpis vitae leo malesuada elementum ut ut elit. Maecenas ut enim varius, sollicitudin nibh ac, dictum enim. Nunc dui lorem.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe13.png', price: 90, category: "Men's Shoes"}

,{ id: 89, name: 'Nike Zoom Air Huarache 2K4', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer faucibus in lectus semper volutpat. Vivamus sed suscipit nulla, vel hendrerit eros. Etiam efficitur tincidunt ex, at maximus diam gravida tincidunt.', colors: ['black'], relatedShoes: [2, 3, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe1.png', price: 75, category: "Womens Shoes"}

,{ id: 90, name: 'Nike Air Zoom Huarache 2K5', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at commodo nunc, ac ultricies urna. Sed malesuada placerat cursus. Sed eget eros dapibus, viverra nunc at, convallis odio. Fusce orci.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe2.png', price: 125, category: "Men's Shoes"}

,{ id: 91, name: 'Nike Zoom Kobe I', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed facilisis magna eros, id egestas magna euismod ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec a auctor.', colors: ['white', 'back'], relatedShoes: [1, 2, 4, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe3.png', price: 85, category: "Womens Shoes"}

,{ id: 92, name: 'Nike Zoom Kobe III', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non eleifend erat, et dictum quam. Nam vehicula cursus justo, et varius risus tempus fermentum. Vivamus finibus luctus laoreet. Vivamus et.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 5, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe4.png', price: 210, category: "Men's Shoes"}

,{ id: 93, name: 'Nike Hyperfuse', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus tortor risus, commodo vel est et, laoreet feugiat massa. Nullam varius blandit diam auctor tristique. Etiam fermentum dignissim justo et lacinia.', colors: ['red', 'white', 'blue'], relatedShoes: [1, 2, 3, 4, 6, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe5.png', price: 165, category: "Womens Shoes"}

,{ id: 94, name: 'Nike HyperDunk Kobe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dictum laoreet congue. Duis convallis, augue a ultricies eleifend, eros risus blandit nibh, non consequat ex nunc id eros. Etiam laoreet.', colors: ['black'], relatedShoes: [1, 2, 3, 4, 5, 7, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe6.png', price: 180, category: "Men's Shoes"}

,{ id: 95, name: 'Nike Zoom Kobe VII', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla non eleifend erat, et dictum quam. Nam vehicula cursus justo, et varius risus tempus fermentum. Vivamus finibus luctus laoreet. Vivamus et.', colors: ['purple', 'gold', 'white'], relatedShoes: [1, 2, 3, 4, 5, 6, 8, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe7.png', price: 90, category: "Womens Shoes"}

,{ id: 96, name: 'Nike Zoom Kobe Venomenom IV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer at commodo nunc, ac ultricies urna. Sed malesuada placerat cursus. Sed eget eros dapibus, viverra nunc at, convallis odio. Fusce orci.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 9, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe8.png', price: 75, category: "Men's Shoes"}

,{ id: 97, name: 'Nike Zoom Kobe Venomenom IV', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam bibendum nisl quam, sit amet aliquam leo vestibulum sit amet. Suspendisse venenatis vulputate dapibus. Nunc mauris ante, molestie sit amet metus.', colors: ['yellow', 'white', 'red', 'green'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 10,11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe9.png', price: 125, category: "Womens Shoes"}

,{ id: 98, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe10.png', price: 125, category: "Men's Shoes"}

,{ id: 99, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe11.png', price: 125, category: "Men's Shoes"}

,{ id: 100, name: 'Generic Shoe', reviews: [['awesome shoe', 5], ['meh', 3], ['this shoe sucks!', 1]], description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in vestibulum lectus. Ut sit amet nunc molestie, faucibus lectus vel, aliquam ex. Nulla ac hendrerit mi, at pretium nulla. Pellentesque.', colors: ['white', 'back'], relatedShoes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13], image: 'https://s3-us-west-1.amazonaws.com/ggrd-imgs/relatedShoe12.png', price: 125, category: "Men's Shoes"}];

module.exports.fakeData = fakeData;

